import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { purchaseOrderStatusUpdate, purchaseOrderDeliveryUpdate, categoryBudgetValues, reservationValues, reservationPeak, notificationTargetId } from '../../src/lib/costNotificationWorkflows.js';

const migration = new URL('../../supabase/migrations/20261004173132_subscriber_costs_assets_notifications.sql', import.meta.url);
const id = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;

test('purchase order approval records spending approval without reporting receipt', () => {
  assert.deepEqual(purchaseOrderStatusUpdate('Approved', { total: 123.45 }), { status: 'Approved', approved_amount: 123.45 });
  assert.deepEqual(purchaseOrderStatusUpdate('Sent', { total: 123.45 }), { status: 'Sent' });
  assert.deepEqual(purchaseOrderDeliveryUpdate('Partial delivery', new Date('2026-10-05T12:00:00Z')), { delivery_status: 'Partial delivery', actual_delivery_date: null });
  assert.deepEqual(purchaseOrderDeliveryUpdate('Received', new Date('2026-10-05T12:00:00Z')), { delivery_status: 'Received', actual_delivery_date: '2026-10-05' });
});

test('cost and reservation forms reject invalid limits and dates', () => {
  assert.equal(notificationTargetId(new URLSearchParams({ reservation: id(42) }), 'reservation', 'reservationId'), id(42));
  assert.equal(notificationTargetId(new URLSearchParams({ id: 'foreign OR 1=1' }), 'id'), null);
  assert.deepEqual(categoryBudgetValues([{ name: ' Electrical ', amount: '1000' }]), { Electrical: 1000 });
  assert.throws(() => categoryBudgetValues([{ name: 'Electrical', amount: -10 }]), /zero or more/);
  assert.throws(() => categoryBudgetValues([{ name: 'Electrical', amount: 10 }, { name: 'electrical', amount: 20 }]), /once/);
  assert.throws(() => categoryBudgetValues([{ name: '__proto__', amount: 1 }]), /another/);
  assert.throws(() => reservationValues({ quantity: 0 }, id(1), id(2)), /greater than zero/);
  assert.throws(() => reservationValues({ quantity: 1, start_date: '2026-10-07', return_due_date: '2026-10-06' }, id(1), id(2)), /on or after/);
  assert.equal(reservationPeak([{ status: 'Reserved', quantity: 1, start_date: '2026-10-01', return_due_date: '2026-10-02' }, { status: 'Checked out', quantity: 1, start_date: '2026-10-04', return_due_date: '2026-10-05' }], '2026-10-01', '2026-10-05'), 1);
});

test('cost workflows emit tenant-scoped transitions, true reservations and deduplicated reminders', async () => {
  const db = new PGlite();
  try {
    await db.exec(await readFile(new URL('./schema.sql', import.meta.url), 'utf8'));
    await db.exec('create table if not exists public.vendors(id uuid primary key default gen_random_uuid(),company_id uuid,name text,contact_name text,email text,phone text,category text,invoice_urls jsonb);');
    await db.exec('create table if not exists public.project_phases(id uuid primary key default gen_random_uuid(),company_id uuid,project_id uuid,name text);');
    await db.exec(await readFile(new URL('../../supabase/migrations/20261003220500_role_based_notifications.sql', import.meta.url), 'utf8'));
    await db.exec("create policy legacy_vendor_requests_open_access on vendor_requests for all to anon,authenticated using(true) with check(true); grant select,insert,update,delete on vendor_requests to anon,authenticated; grant select on profiles to authenticated;");
    await db.exec(await readFile(migration, 'utf8'));
    assert.equal((await db.query("select count(*) n from pg_policies where schemaname='public' and tablename='vendor_requests' and policyname='legacy_vendor_requests_open_access' and permissive='PERMISSIVE' and qual='true' and with_check='true'")).rows[0].n,1,'migration preserves legacy policy rather than deleting it');
    assert.equal((await db.query("select count(*) n from pg_policies where schemaname='public' and tablename='vendor_requests' and permissive='RESTRICTIVE'")).rows[0].n,2,'additive restrictive boundaries constrain legacy permissions');
    assert.equal((await db.query("select has_table_privilege('anon','vendor_requests','SELECT') allowed")).rows[0].allowed,true,'legacy table grant is preserved');
    const C=id(1), OTHER=id(2), P=id(3), ADMIN=id(4), OWNER=id(5), EMP=id(6), FOREIGN=id(7), V=id(8), PO=id(10), TOOL=id(11), PERMIT=id(12), MATERIAL=id(13), REQUEST=id(14);
    const q = (sql, values=[]) => db.query(sql, values);
    const count = async event => Number((await q('select count(*) n from notifications where event_key=$1 and user_id=$2', [event, OWNER])).rows[0].n);
    await q("insert into companies(id,name,timezone) values($1,'Synthetic company','America/Edmonton'),($2,'Other company','UTC')", [C,OTHER]);
    await q("insert into profiles(id,company_id,role,full_name,hourly_rate) values($1,$2,'admin','Synthetic admin',0),($3,$2,'owner','Synthetic owner',0),($4,$2,'employee','Synthetic field',30),($5,$6,'admin','Other user',0)", [ADMIN,C,OWNER,EMP,FOREIGN,OTHER]);
    await db.exec('delete from notifications');
    await q("insert into projects(id,company_id,name,status,budget_cost,material_budget,labour_budget,category_budgets) values($1,$2,'Synthetic project','Active',2000,1000,500,'{\"Electrical\":1000}')", [P,C]);
    await q("insert into vendors(id,company_id,name,insurance_expiry,certification_expiry) values($1,$2,'Synthetic trade','2026-10-15','2026-10-16')",[V,C]);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[ADMIN]);
    await q("insert into project_subcontractors(company_id,project_id,subcontractor_id,status) values($1,$2,$3,'Proposed')",[C,P,V]); assert.equal(await count('subcontractor_assigned'),1);
    await q("update vendors set invoice_urls='[{\"url\":\"https://synthetic.example/invoice.pdf\"}]'::jsonb where id=$1",[V]); assert.equal(await count('subcontractor_invoice_received'),1);
    await q("insert into purchase_orders(id,company_id,project_id,po_number,status,total,subtotal,expected_delivery_date,budget_category) values($1,$2,$3,'PO-1','Pending Approval',950,950,'2026-10-04','Electrical')",[PO,C,P]);
    assert.equal(await count('po_approval_requested'),1);
    await q("update purchase_orders set status='Approved',approved_amount=950 where id=$1",[PO]);
    assert.equal((await q('select actual_delivery_date from purchase_orders where id=$1',[PO])).rows[0].actual_delivery_date,null);
    assert.equal(await count('material_budget_approaching'),1);
    assert.equal(await count('category_budget_approaching'),1);
    await q('update purchase_orders set total=1100,subtotal=1100,supplier_acknowledged_at=now() where id=$1',[PO]);
    assert.equal(await count('po_amount_exceeded'),1);
    assert.equal(await count('po_acknowledged'),1);
    assert.equal(await count('material_budget_exceeded'),1);
    await q("update purchase_orders set delivery_status='Partial delivery' where id=$1",[PO]);
    assert.equal(await count('po_partial_delivery'),1);
    await q("update purchase_orders set delivery_status='Delayed' where id=$1",[PO]);
    assert.equal(await count('po_delivery_delayed'),1);
    await q("insert into project_materials(id,company_id,project_id,custom_material_name,quantity,cost_estimated,status,purchase_order_id,needed_by_date) values($1,$2,$3,'Linked material',10,100,'Ordered',$4,'2026-10-05')",[MATERIAL,C,P,PO]);
    await q("insert into expenses(company_id,project_id,amount,status,purchase_order_id) values($1,$2,1100,'Approved',$3)",[C,P,PO]);
    assert.equal(await count('committed_budget_exceeded'),0,'PO-linked materials and claims do not count a purchase twice');
    await q("insert into time_entries(company_id,project_id,user_id,employee_name,total_hours,status,date) values($1,$2,$3,'Synthetic field',20,'Approved','2026-10-05')",[C,P,EMP]);
    assert.equal(await count('labour_cost_exceeded'),1);
    assert.equal((await q('select cost_rate from time_entries where user_id=$1',[EMP])).rows[0].cost_rate,'30');
    await q("insert into inventory(id,company_id,name,item_type,equipment_status,quantity_on_hand,maintenance_due_date) values($1,$2,'Synthetic saw','Equipment','Available',2,'2026-10-04')",[TOOL,C]);
    await q("update inventory set equipment_status='Damaged' where id=$1",[TOOL]);
    assert.equal(await count('equipment_damaged'),1);
    await q("update inventory set equipment_status='Missing' where id=$1",[TOOL]);
    assert.equal(await count('equipment_missing'),1);
    await q("update inventory set equipment_status='Available' where id=$1",[TOOL]);
    const reserve = (rid, qty, start, end, status='Reserved') => q('insert into inventory_reservations(id,company_id,inventory_id,project_id,assigned_to,quantity,start_date,return_due_date,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9)',[rid,C,TOOL,P,EMP,qty,start,end,status]);
    await reserve(id(21),1,'2026-10-01','2026-10-02');
    await reserve(id(22),1,'2026-10-04','2026-10-05');
    await reserve(id(23),1,'2026-10-01','2026-10-05');
    assert.ok((await q("select count(*) n from notifications where event_key='equipment_reserved' and user_id=$1",[EMP])).rows[0].n>0,'assigned staff receive their own reservation alert');
    assert.equal(await count('inventory_reservation_conflict'),0,'disjoint existing bookings are not added together');
    await reserve(id(24),1,'2026-10-04','2026-10-05','Checked out');
    assert.equal(await count('inventory_reservation_conflict'),1);
    await q("insert into project_permits(id,company_id,project_id,permit_type,status,expiry_date) values($1,$2,$3,'Building','Pending','2026-10-20')",[PERMIT,C,P]);
    await q("update project_permits set status='Information Required' where id=$1",[PERMIT]); assert.equal(await count('permit_information_required'),1);
    await q("update project_permits set status='Approved',inspection_result='Passed' where id=$1",[PERMIT]); assert.equal(await count('permit_approved'),1); assert.equal(await count('inspection_passed'),1);
    await q("update project_permits set inspection_result='Failed' where id=$1",[PERMIT]); assert.equal(await count('inspection_failed'),1);
    await q("insert into vendor_requests(id,company_id,vendor_id,project_id,title,status,created_by) values($1,$2,$3,$4,'Synthetic scope','Sent',$5)",[REQUEST,C,V,P,ADMIN]);
    const token=(await q('select response_token from vendor_requests where id=$1',[REQUEST])).rows[0].response_token;
    await q("select set_config('request.jwt.claim.sub','',false)");
    await assert.rejects(q("select process_vendor_response($1,$2,'view')",[REQUEST,'0'.repeat(64)]),/unavailable|Invalid/);
    const viewed=(await q("select process_vendor_response($1,$2,'view') result",[REQUEST,token])).rows[0].result;
    assert.equal(viewed.title,'Synthetic scope'); assert.ok(!('response_token' in viewed)); assert.ok(!('company_id' in viewed));
    await q("select process_vendor_response($1,$2,'accepted')",[REQUEST,token]); assert.equal(await count('subcontractor_invitation_accepted'),1);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[FOREIGN]);
    await q("select process_vendor_response($1,$2,'quoted',500,'Scope and exclusions')",[REQUEST,token]); assert.equal(await count('subcontractor_quote'),1);
    await q("select process_vendor_response($1,$2,'quoted',500,'Scope and exclusions')",[REQUEST,token]); assert.equal(await count('subcontractor_quote'),1,'identical public retries do not duplicate quote alerts');
    await q("select set_config('request.jwt.claim.sub','',false)");
    await q("update vendor_requests set status='Approved' where id=$1",[REQUEST]); assert.equal(await count('subcontractor_quote_approved'),1);
    await assert.rejects(q("select process_vendor_response($1,$2,'quoted',600,'Changed')",[REQUEST,token]),/closed/);
    await q("select notification_private.costs_reminders('2026-10-06T16:00:00Z')");
    assert.equal(await count('po_delivery_late'),1); assert.equal(await count('permit_expiring'),1); assert.equal(await count('equipment_maintenance_due'),1); assert.equal(await count('equipment_return_overdue'),1); assert.equal(await count('material_needed_unavailable'),1); assert.equal(await count('subcontractor_insurance_expiring'),1); assert.equal(await count('subcontractor_certification_expiring'),1);
    const first=(await q('select count(*) n from notifications')).rows[0].n;
    await q("select notification_private.costs_reminders('2026-10-06T17:00:00Z')"); assert.equal((await q('select count(*) n from notifications')).rows[0].n,first);
    assert.equal((await q('select count(*) n from notifications where company_id=$1',[OTHER])).rows[0].n,0);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[FOREIGN]);
    await assert.rejects(q("update inventory set equipment_status='Missing' where id=$1",[TOOL]),/Company access/);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[ADMIN]);
    await assert.rejects(q('insert into inventory_reservations(company_id,inventory_id,quantity,start_date,return_due_date) values($1,$2,1,now()::date,now()::date)',[OTHER,TOOL]),/Company access/);
    const reminderTypes=(await q("select event_key,related_type from notifications where event_key in ('permit_expiring','material_needed_unavailable')")).rows;
    assert.ok(reminderTypes.some(r=>r.event_key==='permit_expiring'&&r.related_type==='Permit'));
    assert.ok(reminderTypes.some(r=>r.event_key==='material_needed_unavailable'&&r.related_type==='Material'));
    await q("select set_config('request.jwt.claim.sub',$1,false)",[EMP]);
    await assert.rejects(q('update inventory set quantity_on_hand=1000 where id=$1',[TOOL]),/office staff manage warehouse/);
    await assert.rejects(q("update inventory_reservations set quantity=100 where id=$1",[id(22)]),/Management access/);
    await q("select inventory_reservation_action($1,'request_checkout')",[id(22)]);
    await q("select inventory_reservation_action($1,'request_checkout')",[id(22)]);
    assert.equal((await q('select status from inventory_reservations where id=$1',[id(22)])).rows[0].status,'Reserved','field request does not approve checkout');
    assert.equal(await count('equipment_checkout_requested'),1,'request retries do not repeat office alerts');
    await assert.rejects(q("select inventory_reservation_action($1,'confirm_return')",[id(22)]),/Only checked-out/);
    await q("select inventory_reservation_action($1,'confirm_return')",[id(24)]);
    const returned=(await q('select status,returned_at from inventory_reservations where id=$1',[id(24)])).rows[0];
    assert.equal(returned.status,'Returned'); assert.ok(returned.returned_at);
    await q("select inventory_reservation_action($1,'confirm_return')",[id(24)]);
    await assert.rejects(q('select consume_inventory_material($1,1)',[TOOL]),/equipment reservations/);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[ADMIN]);
    const STOCK=id(81); await q("insert into inventory(id,company_id,name,quantity_on_hand,item_type) values($1,$2,'Consumable material',5,'Material')",[STOCK,C]);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[EMP]);
    await assert.rejects(q('select consume_inventory_material($1,6)',[STOCK]),/Insufficient/);
    assert.equal((await q('select quantity_on_hand from inventory where id=$1',[STOCK])).rows[0].quantity_on_hand,'5','failed consumption leaves stock unchanged');
    await assert.rejects(q('select consume_inventory_material($1,1,$2)',[STOCK,P]),/Assigned project/);
    const tx=(await q('select consume_inventory_material($1,2) id',[STOCK])).rows[0].id;
    assert.equal((await q('select quantity_on_hand from inventory where id=$1',[STOCK])).rows[0].quantity_on_hand,'3');
    assert.equal((await q('select user_id from inventory_transactions where id=$1',[tx])).rows[0].user_id,EMP,'actor is derived from the authenticated profile');
    await q("select set_config('request.jwt.claim.sub',$1,false)",[ADMIN]);
    await assert.rejects(q('select refund_inventory_material($1)',[tx]),/Your material/);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[FOREIGN]);
    await assert.rejects(q("select inventory_reservation_action($1,'confirm_return')",[id(24)]),/Assigned reservation unavailable/);
    await assert.rejects(q('select refund_inventory_material($1)',[tx]),/Your material/);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[EMP]);
    await q('select refund_inventory_material($1)',[tx]); await q('select refund_inventory_material($1)',[tx]);
    assert.equal((await q('select quantity_on_hand from inventory where id=$1',[STOCK])).rows[0].quantity_on_hand,'5','retry returns stock once');
    assert.ok((await q('select refunded_at from inventory_transactions where id=$1',[tx])).rows[0].refunded_at,'usage history survives a refund');
    await assert.rejects(q('delete from inventory_transactions where id=$1',[tx]),/office staff manage warehouse/);
    await q("select set_config('request.jwt.claim.sub',$1,false)",[ADMIN]);
    await db.exec('set role authenticated');
    assert.equal((await q('select count(*) n from vendor_requests where id=$1',[REQUEST])).rows[0].n,1,'active same-tenant office retains intended reads');
    await q("select set_config('request.jwt.claim.sub',$1,false)",[FOREIGN]);
    assert.equal((await q('select count(*) n from vendor_requests')).rows[0].n,0,'foreign office cannot read raw rows despite permissive legacy policy');
    assert.equal((await q("update vendor_requests set response_message='Unauthorised write' where id=$1 returning id",[REQUEST])).rows.length,0,'foreign writes remain blocked by the restrictive boundary');
    await q("select set_config('request.jwt.claim.sub',$1,false)",[EMP]);
    assert.equal((await q('select count(*) n from vendor_requests')).rows[0].n,0,'field staff do not obtain raw invitation tokens');
    await db.exec('reset role'); await q("select set_config('request.jwt.claim.sub',$1,false)",[OWNER]); await q('update profiles set is_active=false where id=$1',[ADMIN]); await q("select set_config('request.jwt.claim.sub',$1,false)",[ADMIN]);
    await db.exec('set role authenticated'); assert.equal((await q('select count(*) n from vendor_requests')).rows[0].n,0,'inactive internal account is denied');
    await db.exec('reset role'); await q("select set_config('request.jwt.claim.sub',$1,false)",[OWNER]); await q('update profiles set is_active=true where id=$1',[ADMIN]);
    await q("select set_config('request.jwt.claim.sub','',false)");
    await db.exec('set role anon'); assert.equal((await q('select count(*) n from vendor_requests')).rows[0].n,0,'RLS protects tokens even with legacy permissive policy and grant');
    const publicProjection=(await q("select process_vendor_response($1,$2,'view') result",[REQUEST,token])).rows[0].result;
    assert.equal(publicProjection.title,'Synthetic scope','token holder can view the projected invitation anonymously');
    assert.ok(!('response_token' in publicProjection) && !('company_id' in publicProjection),'public token RPC never exposes raw secrets or tenant rows');
    assert.equal((await q("update vendor_requests set response_message='Anonymous write' where id=$1 returning id",[REQUEST])).rows.length,0,'anonymous recipients cannot mutate raw requests');
    await assert.rejects(q('select notification_private.costs_reminders()'), /permission denied/); await db.exec('reset role');
  } finally { await db.close(); }
});
