-- Additive synthetic fixture from reviewed live column metadata; no customer records.
-- Vector contents are irrelevant to notification workflows and represented as text.
alter table auth.users add column email_confirmed_at timestamptz;
create schema if not exists vault;
create table vault.decrypted_secrets(name text,decrypted_secret text);
create schema if not exists net;
create function net.http_post(url text,body jsonb default '{}'::jsonb,params jsonb default '{}'::jsonb,headers jsonb default '{}'::jsonb,timeout_milliseconds integer default 5000) returns bigint language sql as $$select 1::bigint$$;
create table if not exists public."attachments" (id uuid primary key default gen_random_uuid());
alter table public."attachments" add column if not exists "company_id" uuid;
alter table public."attachments" add column if not exists "related_type" text;
alter table public."attachments" add column if not exists "related_id" uuid;
alter table public."attachments" add column if not exists "file_url" text;
alter table public."attachments" add column if not exists "file_name" text;
alter table public."attachments" add column if not exists "caption" text;
alter table public."attachments" add column if not exists "created_at" timestamptz default now();
create table if not exists public."automation_steps" (id uuid primary key default gen_random_uuid());
alter table public."automation_steps" add column if not exists "automation_id" uuid;
alter table public."automation_steps" add column if not exists "company_id" uuid;
alter table public."automation_steps" add column if not exists "step_order" integer;
alter table public."automation_steps" add column if not exists "action_type" text;
alter table public."automation_steps" add column if not exists "action_config" jsonb;
alter table public."automation_steps" add column if not exists "is_active" boolean;
alter table public."automation_steps" add column if not exists "created_at" timestamptz default now();
create table if not exists public."change_order_approvals" (id uuid primary key default gen_random_uuid());
alter table public."change_order_approvals" add column if not exists "change_order_id" uuid;
alter table public."change_order_approvals" add column if not exists "client_id" uuid;
alter table public."change_order_approvals" add column if not exists "approval_token" text;
alter table public."change_order_approvals" add column if not exists "approval_status" text;
alter table public."change_order_approvals" add column if not exists "sent_at" timestamptz;
alter table public."change_order_approvals" add column if not exists "viewed_at" timestamptz;
alter table public."change_order_approvals" add column if not exists "signed_at" timestamptz;
alter table public."change_order_approvals" add column if not exists "client_ip" text;
alter table public."change_order_approvals" add column if not exists "created_at" timestamptz default now();
create table if not exists public."change_order_line_items" (id uuid primary key default gen_random_uuid());
alter table public."change_order_line_items" add column if not exists "company_id" uuid;
alter table public."change_order_line_items" add column if not exists "change_order_id" uuid;
alter table public."change_order_line_items" add column if not exists "phase_id" uuid;
alter table public."change_order_line_items" add column if not exists "name" text;
alter table public."change_order_line_items" add column if not exists "description" text;
alter table public."change_order_line_items" add column if not exists "quantity" numeric;
alter table public."change_order_line_items" add column if not exists "unit" text;
alter table public."change_order_line_items" add column if not exists "unit_cost" numeric;
alter table public."change_order_line_items" add column if not exists "unit_price" numeric;
alter table public."change_order_line_items" add column if not exists "taxable" boolean;
alter table public."change_order_line_items" add column if not exists "product_id" uuid;
alter table public."change_order_line_items" add column if not exists "display_order" integer;
alter table public."change_order_line_items" add column if not exists "created_at" timestamptz default now();
alter table public."change_order_line_items" add column if not exists "material_cost" numeric;
alter table public."change_order_line_items" add column if not exists "labor_cost" numeric;
alter table public."change_order_line_items" add column if not exists "is_material" boolean;
alter table public."change_order_line_items" add column if not exists "supplier" text;
alter table public."change_order_line_items" add column if not exists "is_optional" boolean;
alter table public."change_order_line_items" add column if not exists "default_selected" boolean;
alter table public."change_order_line_items" add column if not exists "photo_url" text;
create table if not exists public."change_order_phases" (id uuid primary key default gen_random_uuid());
alter table public."change_order_phases" add column if not exists "company_id" uuid;
alter table public."change_order_phases" add column if not exists "change_order_id" uuid;
alter table public."change_order_phases" add column if not exists "phase_name" text;
alter table public."change_order_phases" add column if not exists "scope_of_work" text;
alter table public."change_order_phases" add column if not exists "show_scope_to_client" boolean;
alter table public."change_order_phases" add column if not exists "internal_notes" text;
alter table public."change_order_phases" add column if not exists "photos" text[];
alter table public."change_order_phases" add column if not exists "sort_order" integer;
alter table public."change_order_phases" add column if not exists "created_at" timestamptz default now();
alter table public."change_order_phases" add column if not exists "is_optional" boolean;
alter table public."change_order_phases" add column if not exists "default_selected" boolean;
create table if not exists public."change_orders" (id uuid primary key default gen_random_uuid());
alter table public."change_orders" add column if not exists "company_id" uuid;
alter table public."change_orders" add column if not exists "project_id" uuid;
alter table public."change_orders" add column if not exists "client_id" uuid;
alter table public."change_orders" add column if not exists "title" text;
alter table public."change_orders" add column if not exists "change_order_number" text;
alter table public."change_orders" add column if not exists "status" text;
alter table public."change_orders" add column if not exists "issue_date" date;
alter table public."change_orders" add column if not exists "notes" text;
alter table public."change_orders" add column if not exists "client_message" text;
alter table public."change_orders" add column if not exists "terms" text;
alter table public."change_orders" add column if not exists "overall_scope" text;
alter table public."change_orders" add column if not exists "show_overall_scope" boolean;
alter table public."change_orders" add column if not exists "hero_image_url" text;
alter table public."change_orders" add column if not exists "end_photos" text[];
alter table public."change_orders" add column if not exists "documents" jsonb;
alter table public."change_orders" add column if not exists "subtotal" numeric;
alter table public."change_orders" add column if not exists "tax" numeric;
alter table public."change_orders" add column if not exists "total" numeric;
alter table public."change_orders" add column if not exists "created_at" timestamptz default now();
alter table public."change_orders" add column if not exists "client_selected_items_json" text;
alter table public."change_orders" add column if not exists "margin" numeric;
alter table public."change_orders" add column if not exists "margin_adjustment_type" text;
alter table public."change_orders" add column if not exists "automation_stage" integer;
alter table public."change_orders" add column if not exists "budget_synced_at" timestamptz;
create table if not exists public."client_communications" (id uuid primary key default gen_random_uuid());
alter table public."client_communications" add column if not exists "company_id" uuid;
alter table public."client_communications" add column if not exists "client_id" uuid;
alter table public."client_communications" add column if not exists "type" text;
alter table public."client_communications" add column if not exists "subject" text;
alter table public."client_communications" add column if not exists "message" text;
alter table public."client_communications" add column if not exists "direction" text;
alter table public."client_communications" add column if not exists "status" text;
alter table public."client_communications" add column if not exists "sent_by" text;
alter table public."client_communications" add column if not exists "created_at" timestamptz default now();
create table if not exists public."client_reminders" (id uuid primary key default gen_random_uuid());
alter table public."client_reminders" add column if not exists "company_id" uuid;
alter table public."client_reminders" add column if not exists "client_id" uuid;
alter table public."client_reminders" add column if not exists "title" text;
alter table public."client_reminders" add column if not exists "description" text;
alter table public."client_reminders" add column if not exists "due_date" date;
alter table public."client_reminders" add column if not exists "priority" text;
alter table public."client_reminders" add column if not exists "status" text;
alter table public."client_reminders" add column if not exists "assigned_to" uuid;
alter table public."client_reminders" add column if not exists "created_at" timestamptz default now();
create table if not exists public."client_segments" (id uuid primary key default gen_random_uuid());
alter table public."client_segments" add column if not exists "company_id" uuid;
alter table public."client_segments" add column if not exists "name" text;
alter table public."client_segments" add column if not exists "description" text;
alter table public."client_segments" add column if not exists "filters" text;
alter table public."client_segments" add column if not exists "is_shared" boolean;
alter table public."client_segments" add column if not exists "created_by" text;
alter table public."client_segments" add column if not exists "created_at" timestamptz default now();
create table if not exists public."clients" (id uuid primary key default gen_random_uuid());
alter table public."clients" add column if not exists "company_id" uuid;
alter table public."clients" add column if not exists "name" text;
alter table public."clients" add column if not exists "first_name" text;
alter table public."clients" add column if not exists "surname" text;
alter table public."clients" add column if not exists "email" text;
alter table public."clients" add column if not exists "phone" text;
alter table public."clients" add column if not exists "site_address" text;
alter table public."clients" add column if not exists "billing_address" text;
alter table public."clients" add column if not exists "notes" text;
alter table public."clients" add column if not exists "type" text;
alter table public."clients" add column if not exists "created_at" timestamptz default now();
alter table public."clients" add column if not exists "primary_contact_name" text;
alter table public."clients" add column if not exists "tags" text[];
alter table public."clients" add column if not exists "portal_features" jsonb;
create table if not exists public."companies" (id uuid primary key default gen_random_uuid());
alter table public."companies" add column if not exists "name" text;
alter table public."companies" add column if not exists "plan_id" text;
alter table public."companies" add column if not exists "subscription_status" text;
alter table public."companies" add column if not exists "stripe_customer_id" text;
alter table public."companies" add column if not exists "created_at" timestamptz default now();
alter table public."companies" add column if not exists "phone" text;
alter table public."companies" add column if not exists "website" text;
alter table public."companies" add column if not exists "timezone" text;
alter table public."companies" add column if not exists "gst_rate" numeric;
alter table public."companies" add column if not exists "default_quote_terms" text;
alter table public."companies" add column if not exists "quote_number_prefix" text;
alter table public."companies" add column if not exists "invoice_number_prefix" text;
alter table public."companies" add column if not exists "project_number_prefix" text;
alter table public."companies" add column if not exists "company_logo_url" text;
alter table public."companies" add column if not exists "next_project_number" integer;
alter table public."companies" add column if not exists "next_invoice_number" integer;
alter table public."companies" add column if not exists "next_quote_number" integer;
alter table public."companies" add column if not exists "next_change_order_number" integer;
alter table public."companies" add column if not exists "change_order_prefix" text;
alter table public."companies" add column if not exists "next_po_number" integer;
alter table public."companies" add column if not exists "po_number_prefix" text;
alter table public."companies" add column if not exists "stripe_account_id" text;
alter table public."companies" add column if not exists "notification_emails" text[];
alter table public."companies" add column if not exists "settings" jsonb;
alter table public."companies" add column if not exists "subscription_tier" text;
alter table public."companies" add column if not exists "stripe_charges_enabled" boolean;
alter table public."companies" add column if not exists "qbo_realm_id" text;
alter table public."companies" add column if not exists "qbo_connected" boolean;
alter table public."companies" add column if not exists "logo_url" text;
alter table public."companies" add column if not exists "doc_prefix_quote" text;
alter table public."companies" add column if not exists "doc_prefix_invoice" text;
alter table public."companies" add column if not exists "max_users" integer;
create table if not exists public."company_resources" (id uuid primary key default gen_random_uuid());
alter table public."company_resources" add column if not exists "company_id" uuid;
alter table public."company_resources" add column if not exists "project_id" uuid;
alter table public."company_resources" add column if not exists "name" text;
alter table public."company_resources" add column if not exists "file_name" text;
alter table public."company_resources" add column if not exists "file_url" text;
alter table public."company_resources" add column if not exists "created_at" timestamptz default now();
create table if not exists public."contractor_portal_files" (id uuid primary key default gen_random_uuid());
alter table public."contractor_portal_files" add column if not exists "company_id" uuid;
alter table public."contractor_portal_files" add column if not exists "project_id" uuid;
alter table public."contractor_portal_files" add column if not exists "file_name" text;
alter table public."contractor_portal_files" add column if not exists "file_url" text;
alter table public."contractor_portal_files" add column if not exists "description" text;
alter table public."contractor_portal_files" add column if not exists "created_at" timestamptz default now();
create table if not exists public."expenses" (id uuid primary key default gen_random_uuid());
alter table public."expenses" add column if not exists "company_id" uuid;
alter table public."expenses" add column if not exists "user_id" uuid;
alter table public."expenses" add column if not exists "user_email" text;
alter table public."expenses" add column if not exists "employee_name" text;
alter table public."expenses" add column if not exists "project_id" uuid;
alter table public."expenses" add column if not exists "date" date;
alter table public."expenses" add column if not exists "category" text;
alter table public."expenses" add column if not exists "amount" numeric;
alter table public."expenses" add column if not exists "description" text;
alter table public."expenses" add column if not exists "payment_method" text;
alter table public."expenses" add column if not exists "receipt_url" text;
alter table public."expenses" add column if not exists "status" text;
alter table public."expenses" add column if not exists "admin_notes" text;
alter table public."expenses" add column if not exists "created_at" timestamptz default now();
alter table public."expenses" add column if not exists "qbo_purchase_id" text;
alter table public."expenses" add column if not exists "qbo_sync_status" text;
alter table public."expenses" add column if not exists "qbo_sync_error" text;
create table if not exists public."goals" (id uuid primary key default gen_random_uuid());
alter table public."goals" add column if not exists "company_id" uuid;
alter table public."goals" add column if not exists "title" text;
alter table public."goals" add column if not exists "target_value" numeric;
alter table public."goals" add column if not exists "current_value" numeric;
alter table public."goals" add column if not exists "metric_type" text;
alter table public."goals" add column if not exists "deadline" date;
alter table public."goals" add column if not exists "created_at" timestamptz default now();
create table if not exists public."help_docs" (id uuid primary key default gen_random_uuid());
alter table public."help_docs" add column if not exists "title" text;
alter table public."help_docs" add column if not exists "content" text;
alter table public."help_docs" add column if not exists "embedding" text;
create table if not exists public."help_faqs" (id uuid primary key default gen_random_uuid());
alter table public."help_faqs" add column if not exists "slug" text;
alter table public."help_faqs" add column if not exists "feature_area" text;
alter table public."help_faqs" add column if not exists "audience" text;
alter table public."help_faqs" add column if not exists "intent" text;
alter table public."help_faqs" add column if not exists "question" text;
alter table public."help_faqs" add column if not exists "answer_short" text;
alter table public."help_faqs" add column if not exists "answer_long" text;
alter table public."help_faqs" add column if not exists "route" text;
alter table public."help_faqs" add column if not exists "search_terms" text[];
alter table public."help_faqs" add column if not exists "priority" smallint;
alter table public."help_faqs" add column if not exists "requires_admin" boolean;
alter table public."help_faqs" add column if not exists "is_active" boolean;
alter table public."help_faqs" add column if not exists "source_key" text;
alter table public."help_faqs" add column if not exists "last_verified_at" date;
alter table public."help_faqs" add column if not exists "created_at" timestamptz default now();
alter table public."help_faqs" add column if not exists "updated_at" timestamptz default now();
alter table public."help_faqs" add column if not exists "embedding" text;
alter table public."help_faqs" add column if not exists "article_type" text;
alter table public."help_faqs" add column if not exists "read_minutes" smallint;
alter table public."help_faqs" add column if not exists "related_slugs" text[];
create table if not exists public."integration_mappings" (id uuid primary key default gen_random_uuid());
alter table public."integration_mappings" add column if not exists "company_id" uuid;
alter table public."integration_mappings" add column if not exists "category_type" text;
alter table public."integration_mappings" add column if not exists "local_value" text;
alter table public."integration_mappings" add column if not exists "qbo_account_id" text;
alter table public."integration_mappings" add column if not exists "qbo_account_name" text;
alter table public."integration_mappings" add column if not exists "created_at" timestamptz default now();
alter table public."integration_mappings" add column if not exists "updated_at" timestamptz default now();
create table if not exists public."inventory" (id uuid primary key default gen_random_uuid());
alter table public."inventory" add column if not exists "company_id" uuid;
alter table public."inventory" add column if not exists "name" text;
alter table public."inventory" add column if not exists "sku" text;
alter table public."inventory" add column if not exists "category" text;
alter table public."inventory" add column if not exists "sub_category" text;
alter table public."inventory" add column if not exists "tertiary_category" text;
alter table public."inventory" add column if not exists "unit" text;
alter table public."inventory" add column if not exists "material_cost" numeric;
alter table public."inventory" add column if not exists "labor_cost" numeric;
alter table public."inventory" add column if not exists "cost" numeric;
alter table public."inventory" add column if not exists "price" numeric;
alter table public."inventory" add column if not exists "supplier" text;
alter table public."inventory" add column if not exists "vendor_url" text;
alter table public."inventory" add column if not exists "description" text;
alter table public."inventory" add column if not exists "image_url" text;
alter table public."inventory" add column if not exists "taxable" boolean;
alter table public."inventory" add column if not exists "project_name" text;
alter table public."inventory" add column if not exists "created_at" timestamptz default now();
alter table public."inventory" add column if not exists "updated_at" timestamptz default now();
alter table public."inventory" add column if not exists "quantity_on_hand" numeric;
alter table public."inventory" add column if not exists "reorder_point" numeric;
alter table public."inventory" add column if not exists "location" text;
create table if not exists public."inventory_logs" (id uuid primary key default gen_random_uuid());
alter table public."inventory_logs" add column if not exists "company_id" uuid;
alter table public."inventory_logs" add column if not exists "user_id" uuid;
alter table public."inventory_logs" add column if not exists "project_id" uuid;
alter table public."inventory_logs" add column if not exists "item_name" text;
alter table public."inventory_logs" add column if not exists "quantity" numeric;
alter table public."inventory_logs" add column if not exists "unit" text;
alter table public."inventory_logs" add column if not exists "date" date;
alter table public."inventory_logs" add column if not exists "notes" text;
alter table public."inventory_logs" add column if not exists "created_at" timestamptz default now();
create table if not exists public."inventory_transactions" (id uuid primary key default gen_random_uuid());
alter table public."inventory_transactions" add column if not exists "company_id" uuid;
alter table public."inventory_transactions" add column if not exists "inventory_id" uuid;
alter table public."inventory_transactions" add column if not exists "employee_name" text;
alter table public."inventory_transactions" add column if not exists "project_name" text;
alter table public."inventory_transactions" add column if not exists "quantity_changed" numeric;
alter table public."inventory_transactions" add column if not exists "transaction_type" text;
alter table public."inventory_transactions" add column if not exists "notes" text;
alter table public."inventory_transactions" add column if not exists "created_at" timestamptz default now();
create table if not exists public."invoice_line_items" (id uuid primary key default gen_random_uuid());
alter table public."invoice_line_items" add column if not exists "company_id" uuid;
alter table public."invoice_line_items" add column if not exists "invoice_id" uuid;
alter table public."invoice_line_items" add column if not exists "name" text;
alter table public."invoice_line_items" add column if not exists "amount" numeric;
alter table public."invoice_line_items" add column if not exists "created_at" timestamptz default now();
alter table public."invoice_line_items" add column if not exists "description" text;
alter table public."invoice_line_items" add column if not exists "taxable" boolean;
alter table public."invoice_line_items" add column if not exists "display_order" integer;
alter table public."invoice_line_items" add column if not exists "unit" text;
alter table public."invoice_line_items" add column if not exists "quantity" numeric;
alter table public."invoice_line_items" add column if not exists "unit_price" numeric;
alter table public."invoice_line_items" add column if not exists "line_total" numeric;
alter table public."invoice_line_items" add column if not exists "phase_id" uuid;
create table if not exists public."invoice_payment_schedules" (id uuid primary key default gen_random_uuid());
alter table public."invoice_payment_schedules" add column if not exists "company_id" uuid;
alter table public."invoice_payment_schedules" add column if not exists "invoice_id" uuid;
alter table public."invoice_payment_schedules" add column if not exists "payment_name" text;
alter table public."invoice_payment_schedules" add column if not exists "due_event" text;
alter table public."invoice_payment_schedules" add column if not exists "amount" numeric;
alter table public."invoice_payment_schedules" add column if not exists "amount_paid" numeric;
alter table public."invoice_payment_schedules" add column if not exists "status" text;
alter table public."invoice_payment_schedules" add column if not exists "sort_order" integer;
alter table public."invoice_payment_schedules" add column if not exists "created_at" timestamptz default now();
alter table public."invoice_payment_schedules" add column if not exists "paid_date" date;
alter table public."invoice_payment_schedules" add column if not exists "amount_type" text;
alter table public."invoice_payment_schedules" add column if not exists "percentage" numeric;
alter table public."invoice_payment_schedules" add column if not exists "due_date" date;
create table if not exists public."invoice_phases" (id uuid primary key default gen_random_uuid());
alter table public."invoice_phases" add column if not exists "company_id" uuid;
alter table public."invoice_phases" add column if not exists "invoice_id" uuid;
alter table public."invoice_phases" add column if not exists "phase_name" text;
alter table public."invoice_phases" add column if not exists "scope_of_work" text;
alter table public."invoice_phases" add column if not exists "sort_order" integer;
create table if not exists public."invoices" (id uuid primary key default gen_random_uuid());
alter table public."invoices" add column if not exists "company_id" uuid;
alter table public."invoices" add column if not exists "client_id" uuid;
alter table public."invoices" add column if not exists "quote_id" uuid;
alter table public."invoices" add column if not exists "status" text;
alter table public."invoices" add column if not exists "total" numeric;
alter table public."invoices" add column if not exists "created_at" timestamptz default now();
alter table public."invoices" add column if not exists "project_id" uuid;
alter table public."invoices" add column if not exists "invoice_number" text;
alter table public."invoices" add column if not exists "issue_date" date;
alter table public."invoices" add column if not exists "due_date" date;
alter table public."invoices" add column if not exists "site_address" text;
alter table public."invoices" add column if not exists "subtotal" numeric;
alter table public."invoices" add column if not exists "tax" numeric;
alter table public."invoices" add column if not exists "amount_paid" numeric;
alter table public."invoices" add column if not exists "balance_due" numeric;
alter table public."invoices" add column if not exists "deposit_amount" numeric;
alter table public."invoices" add column if not exists "has_payment_schedule" boolean;
alter table public."invoices" add column if not exists "notes" text;
alter table public."invoices" add column if not exists "billing_address" text;
alter table public."invoices" add column if not exists "due_terms" text;
alter table public."invoices" add column if not exists "show_notes" boolean;
alter table public."invoices" add column if not exists "internal_notes" text;
alter table public."invoices" add column if not exists "discount_amount" numeric;
alter table public."invoices" add column if not exists "discount_type" text;
alter table public."invoices" add column if not exists "change_order_id" uuid;
alter table public."invoices" add column if not exists "last_reminder_sent_at" timestamptz;
alter table public."invoices" add column if not exists "automation_stage" integer;
create table if not exists public."knowledge_chunks" (id uuid primary key default gen_random_uuid());
alter table public."knowledge_chunks" add column if not exists "slug" text;
alter table public."knowledge_chunks" add column if not exists "title" text;
alter table public."knowledge_chunks" add column if not exists "feature_area" text;
alter table public."knowledge_chunks" add column if not exists "subtopic" text;
alter table public."knowledge_chunks" add column if not exists "audience" text;
alter table public."knowledge_chunks" add column if not exists "chunk_type" text;
alter table public."knowledge_chunks" add column if not exists "summary" text;
alter table public."knowledge_chunks" add column if not exists "content" text;
alter table public."knowledge_chunks" add column if not exists "route" text;
alter table public."knowledge_chunks" add column if not exists "search_terms" text[];
alter table public."knowledge_chunks" add column if not exists "priority" smallint;
alter table public."knowledge_chunks" add column if not exists "requires_admin" boolean;
alter table public."knowledge_chunks" add column if not exists "is_active" boolean;
alter table public."knowledge_chunks" add column if not exists "source_key" text;
alter table public."knowledge_chunks" add column if not exists "last_verified_at" date;
alter table public."knowledge_chunks" add column if not exists "embedding_input" text;
alter table public."knowledge_chunks" add column if not exists "content_hash" text;
alter table public."knowledge_chunks" add column if not exists "embedding_model" text;
alter table public."knowledge_chunks" add column if not exists "embedding" text;
alter table public."knowledge_chunks" add column if not exists "embedding_updated_at" timestamptz;
alter table public."knowledge_chunks" add column if not exists "created_at" timestamptz default now();
alter table public."knowledge_chunks" add column if not exists "updated_at" timestamptz default now();
create table if not exists public."knowledge_chunks_needing_embedding" (id uuid primary key default gen_random_uuid());
alter table public."knowledge_chunks_needing_embedding" add column if not exists "slug" text;
alter table public."knowledge_chunks_needing_embedding" add column if not exists "title" text;
alter table public."knowledge_chunks_needing_embedding" add column if not exists "feature_area" text;
alter table public."knowledge_chunks_needing_embedding" add column if not exists "embedding_model" text;
alter table public."knowledge_chunks_needing_embedding" add column if not exists "embedding_input" text;
alter table public."knowledge_chunks_needing_embedding" add column if not exists "content_hash" text;
create table if not exists public."leads" (id uuid primary key default gen_random_uuid());
alter table public."leads" add column if not exists "company_id" uuid;
alter table public."leads" add column if not exists "contact_name" text;
alter table public."leads" add column if not exists "source" text;
alter table public."leads" add column if not exists "value_estimate" numeric;
alter table public."leads" add column if not exists "pipeline_stage" text;
alter table public."leads" add column if not exists "created_at" timestamptz default now();
alter table public."leads" add column if not exists "contact_email" text;
alter table public."leads" add column if not exists "contact_phone" text;
alter table public."leads" add column if not exists "priority" text;
alter table public."leads" add column if not exists "next_follow_up_date" date;
alter table public."leads" add column if not exists "assigned_to" text;
alter table public."leads" add column if not exists "description" text;
alter table public."leads" add column if not exists "notes" text;
alter table public."leads" add column if not exists "site_address" text;
alter table public."leads" add column if not exists "photos" jsonb;
alter table public."leads" add column if not exists "documents" jsonb;
alter table public."leads" add column if not exists "client_id" uuid;
create table if not exists public."messages" (id uuid primary key default gen_random_uuid());
alter table public."messages" add column if not exists "company_id" uuid;
alter table public."messages" add column if not exists "client_id" uuid;
alter table public."messages" add column if not exists "sender_type" text;
alter table public."messages" add column if not exists "sender_name" text;
alter table public."messages" add column if not exists "subject" text;
alter table public."messages" add column if not exists "message_body" text;
alter table public."messages" add column if not exists "is_read" boolean;
alter table public."messages" add column if not exists "created_at" timestamptz default now();
create table if not exists public."notes" (id uuid primary key default gen_random_uuid());
alter table public."notes" add column if not exists "company_id" uuid;
alter table public."notes" add column if not exists "related_type" text;
alter table public."notes" add column if not exists "related_id" uuid;
alter table public."notes" add column if not exists "content" text;
alter table public."notes" add column if not exists "category" text;
alter table public."notes" add column if not exists "author_name" text;
alter table public."notes" add column if not exists "created_at" timestamptz default now();
alter table public."notes" add column if not exists "is_pinned" boolean;
alter table public."notes" add column if not exists "mention_user_ids" uuid[];
create table if not exists public."notifications" (id uuid primary key default gen_random_uuid());
alter table public."notifications" add column if not exists "company_id" uuid;
alter table public."notifications" add column if not exists "type" text;
alter table public."notifications" add column if not exists "status" text;
alter table public."notifications" add column if not exists "metadata" jsonb;
alter table public."notifications" add column if not exists "created_at" timestamptz default now();
alter table public."notifications" add column if not exists "user_id" uuid;
alter table public."notifications" add column if not exists "action_url" text;
alter table public."notifications" add column if not exists "title" text;
alter table public."notifications" add column if not exists "body" text;
alter table public."notifications" add column if not exists "is_read" boolean;
alter table public."notifications" add column if not exists "related_type" text;
alter table public."notifications" add column if not exists "related_id" uuid;
alter table public."notifications" add column if not exists "severity" text;
alter table public."notifications" add column if not exists "category" text;
alter table public."notifications" add column if not exists "event_key" text;
alter table public."notifications" add column if not exists "dedupe_key" text;
create table if not exists public."payments" (id uuid primary key default gen_random_uuid());
alter table public."payments" add column if not exists "company_id" uuid;
alter table public."payments" add column if not exists "invoice_id" uuid;
alter table public."payments" add column if not exists "schedule_item_id" uuid;
alter table public."payments" add column if not exists "amount" numeric;
alter table public."payments" add column if not exists "payment_method" text;
alter table public."payments" add column if not exists "notes" text;
alter table public."payments" add column if not exists "created_at" timestamptz default now();
alter table public."payments" add column if not exists "payment_date" date;
create table if not exists public."pdf_settings" (id uuid primary key default gen_random_uuid());
alter table public."pdf_settings" add column if not exists "company_id" uuid;
alter table public."pdf_settings" add column if not exists "template" text;
alter table public."pdf_settings" add column if not exists "primary_color" text;
alter table public."pdf_settings" add column if not exists "accent_color" text;
alter table public."pdf_settings" add column if not exists "header_background_color" text;
alter table public."pdf_settings" add column if not exists "header_text_color" text;
alter table public."pdf_settings" add column if not exists "footer_text" text;
alter table public."pdf_settings" add column if not exists "footer_color" text;
alter table public."pdf_settings" add column if not exists "show_logo" boolean;
alter table public."pdf_settings" add column if not exists "show_company_info" boolean;
alter table public."pdf_settings" add column if not exists "show_payment_terms" boolean;
alter table public."pdf_settings" add column if not exists "font_family" text;
alter table public."pdf_settings" add column if not exists "font_size_base" integer;
alter table public."pdf_settings" add column if not exists "page_layout" text;
alter table public."pdf_settings" add column if not exists "highlight_totals" boolean;
alter table public."pdf_settings" add column if not exists "item_border_style" text;
alter table public."pdf_settings" add column if not exists "created_at" timestamptz default now();
alter table public."pdf_settings" add column if not exists "updated_at" timestamptz default now();
create table if not exists public."phase_templates" (id uuid primary key default gen_random_uuid());
alter table public."phase_templates" add column if not exists "company_id" uuid;
alter table public."phase_templates" add column if not exists "template_name" text;
alter table public."phase_templates" add column if not exists "description" text;
alter table public."phase_templates" add column if not exists "phase_name" text;
alter table public."phase_templates" add column if not exists "scope_of_work" text;
alter table public."phase_templates" add column if not exists "line_items_json" text;
alter table public."phase_templates" add column if not exists "is_active" boolean;
alter table public."phase_templates" add column if not exists "created_at" timestamptz default now();
create table if not exists public."plans" (id uuid primary key default gen_random_uuid());
alter table public."plans" add column if not exists "plan_id" text;
alter table public."plans" add column if not exists "name" text;
alter table public."plans" add column if not exists "price_monthly" numeric;
alter table public."plans" add column if not exists "price_yearly" numeric;
alter table public."plans" add column if not exists "max_users" integer;
alter table public."plans" add column if not exists "max_quotes_per_month" integer;
alter table public."plans" add column if not exists "features" jsonb;
alter table public."plans" add column if not exists "created_at" timestamptz default now();
create table if not exists public."product_categories" (id uuid primary key default gen_random_uuid());
alter table public."product_categories" add column if not exists "company_id" uuid;
alter table public."product_categories" add column if not exists "main_category" text;
alter table public."product_categories" add column if not exists "sub_category" text;
alter table public."product_categories" add column if not exists "tertiary_category" text;
alter table public."product_categories" add column if not exists "created_at" timestamptz default now();
create table if not exists public."products" (id uuid primary key default gen_random_uuid());
alter table public."products" add column if not exists "company_id" uuid;
alter table public."products" add column if not exists "name" text;
alter table public."products" add column if not exists "description" text;
alter table public."products" add column if not exists "cost" numeric;
alter table public."products" add column if not exists "price" numeric;
alter table public."products" add column if not exists "unit" text;
alter table public."products" add column if not exists "taxable" boolean;
alter table public."products" add column if not exists "image_url" text;
alter table public."products" add column if not exists "category" text;
alter table public."products" add column if not exists "created_at" timestamptz default now();
alter table public."products" add column if not exists "sub_category" text;
alter table public."products" add column if not exists "tertiary_category" text;
alter table public."products" add column if not exists "sku" text;
alter table public."products" add column if not exists "supplier" text;
alter table public."products" add column if not exists "material_cost" numeric;
alter table public."products" add column if not exists "labor_cost" numeric;
alter table public."products" add column if not exists "vendor_url" text;
create table if not exists public."profiles" (id uuid primary key default gen_random_uuid());
alter table public."profiles" add column if not exists "company_id" uuid;
alter table public."profiles" add column if not exists "full_name" text;
alter table public."profiles" add column if not exists "role" text;
alter table public."profiles" add column if not exists "created_at" timestamptz default now();
alter table public."profiles" add column if not exists "permissions" jsonb;
alter table public."profiles" add column if not exists "hourly_rate" numeric;
alter table public."profiles" add column if not exists "qbo_employee_id" text;
alter table public."profiles" add column if not exists "qbo_vendor_id" text;
alter table public."profiles" add column if not exists "dashboard_layout" jsonb;
alter table public."profiles" add column if not exists "onboarding_completed" boolean;
alter table public."profiles" add column if not exists "is_active" boolean;
alter table public."profiles" add column if not exists "phone" text;
alter table public."profiles" add column if not exists "email" text;
alter table public."profiles" add column if not exists "notify_action_required_only" boolean;
create table if not exists public."project_allocations" (id uuid primary key default gen_random_uuid());
alter table public."project_allocations" add column if not exists "company_id" uuid;
alter table public."project_allocations" add column if not exists "project_id" uuid;
alter table public."project_allocations" add column if not exists "task_id" uuid;
alter table public."project_allocations" add column if not exists "user_id" uuid;
alter table public."project_allocations" add column if not exists "allocated_hours" numeric;
alter table public."project_allocations" add column if not exists "utilization_percentage" numeric;
alter table public."project_allocations" add column if not exists "allocation_start_date" date;
alter table public."project_allocations" add column if not exists "allocation_end_date" date;
alter table public."project_allocations" add column if not exists "created_at" timestamptz default now();
create table if not exists public."project_daily_logs" (id uuid primary key default gen_random_uuid());
alter table public."project_daily_logs" add column if not exists "company_id" uuid;
alter table public."project_daily_logs" add column if not exists "project_id" uuid;
alter table public."project_daily_logs" add column if not exists "user_id" uuid;
alter table public."project_daily_logs" add column if not exists "date" date;
alter table public."project_daily_logs" add column if not exists "weather" text;
alter table public."project_daily_logs" add column if not exists "crew_on_site" text;
alter table public."project_daily_logs" add column if not exists "summary" text;
alter table public."project_daily_logs" add column if not exists "blockers" text;
alter table public."project_daily_logs" add column if not exists "safety_concerns" text;
alter table public."project_daily_logs" add column if not exists "materials_used" text;
alter table public."project_daily_logs" add column if not exists "next_steps" text;
alter table public."project_daily_logs" add column if not exists "photos" jsonb;
alter table public."project_daily_logs" add column if not exists "created_at" timestamptz default now();
alter table public."project_daily_logs" add column if not exists "lead_id" uuid;
alter table public."project_daily_logs" add column if not exists "category" text;
alter table public."project_daily_logs" add column if not exists "client_id" uuid;
alter table public."project_daily_logs" add column if not exists "mention_user_ids" uuid[];
create table if not exists public."project_documents" (id uuid primary key default gen_random_uuid());
alter table public."project_documents" add column if not exists "company_id" uuid;
alter table public."project_documents" add column if not exists "project_id" uuid;
alter table public."project_documents" add column if not exists "file_name" text;
alter table public."project_documents" add column if not exists "file_url" text;
alter table public."project_documents" add column if not exists "doc_type" text;
alter table public."project_documents" add column if not exists "vendor_name" text;
alter table public."project_documents" add column if not exists "amount" numeric;
alter table public."project_documents" add column if not exists "notes" text;
alter table public."project_documents" add column if not exists "created_at" timestamptz default now();
create table if not exists public."project_drawings" (id uuid primary key default gen_random_uuid());
alter table public."project_drawings" add column if not exists "company_id" uuid;
alter table public."project_drawings" add column if not exists "project_id" uuid;
alter table public."project_drawings" add column if not exists "file_name" text;
alter table public."project_drawings" add column if not exists "file_url" text;
alter table public."project_drawings" add column if not exists "drawing_type" text;
alter table public."project_drawings" add column if not exists "title" text;
alter table public."project_drawings" add column if not exists "revision" text;
alter table public."project_drawings" add column if not exists "notes" text;
alter table public."project_drawings" add column if not exists "created_at" timestamptz default now();
create table if not exists public."project_issues" (id uuid primary key default gen_random_uuid());
alter table public."project_issues" add column if not exists "company_id" uuid;
alter table public."project_issues" add column if not exists "project_id" uuid;
alter table public."project_issues" add column if not exists "title" text;
alter table public."project_issues" add column if not exists "description" text;
alter table public."project_issues" add column if not exists "severity" text;
alter table public."project_issues" add column if not exists "status" text;
alter table public."project_issues" add column if not exists "created_at" timestamptz default now();
alter table public."project_issues" add column if not exists "client_visible" boolean;
alter table public."project_issues" add column if not exists "phase_id" uuid;
alter table public."project_issues" add column if not exists "owner_name" text;
create table if not exists public."project_materials" (id uuid primary key default gen_random_uuid());
alter table public."project_materials" add column if not exists "company_id" uuid;
alter table public."project_materials" add column if not exists "project_id" uuid;
alter table public."project_materials" add column if not exists "phase_id" uuid;
alter table public."project_materials" add column if not exists "custom_material_name" text;
alter table public."project_materials" add column if not exists "quantity" numeric;
alter table public."project_materials" add column if not exists "unit" text;
alter table public."project_materials" add column if not exists "cost_estimated" numeric;
alter table public."project_materials" add column if not exists "cost_actual" numeric;
alter table public."project_materials" add column if not exists "status" text;
alter table public."project_materials" add column if not exists "needed_by_date" date;
alter table public."project_materials" add column if not exists "created_at" timestamptz default now();
alter table public."project_materials" add column if not exists "order_by_date" date;
alter table public."project_materials" add column if not exists "supplier" text;
alter table public."project_materials" add column if not exists "notes" text;
create table if not exists public."project_milestones" (id uuid primary key default gen_random_uuid());
alter table public."project_milestones" add column if not exists "company_id" uuid;
alter table public."project_milestones" add column if not exists "project_id" uuid;
alter table public."project_milestones" add column if not exists "title" text;
alter table public."project_milestones" add column if not exists "description" text;
alter table public."project_milestones" add column if not exists "due_date_target" date;
alter table public."project_milestones" add column if not exists "status" text;
alter table public."project_milestones" add column if not exists "created_at" timestamptz default now();
alter table public."project_milestones" add column if not exists "client_visible" boolean;
create table if not exists public."project_permits" (id uuid primary key default gen_random_uuid());
alter table public."project_permits" add column if not exists "company_id" uuid;
alter table public."project_permits" add column if not exists "project_id" uuid;
alter table public."project_permits" add column if not exists "permit_type" text;
alter table public."project_permits" add column if not exists "permit_number" text;
alter table public."project_permits" add column if not exists "issued_by" text;
alter table public."project_permits" add column if not exists "issue_date" date;
alter table public."project_permits" add column if not exists "expiry_date" date;
alter table public."project_permits" add column if not exists "status" text;
alter table public."project_permits" add column if not exists "description" text;
alter table public."project_permits" add column if not exists "notes" text;
alter table public."project_permits" add column if not exists "file_url" text;
alter table public."project_permits" add column if not exists "file_name" text;
alter table public."project_permits" add column if not exists "created_at" timestamptz default now();
create table if not exists public."project_phases" (id uuid primary key default gen_random_uuid());
alter table public."project_phases" add column if not exists "company_id" uuid;
alter table public."project_phases" add column if not exists "project_id" uuid;
alter table public."project_phases" add column if not exists "name" text;
alter table public."project_phases" add column if not exists "phase_order" integer;
alter table public."project_phases" add column if not exists "status" text;
alter table public."project_phases" add column if not exists "client_visible" boolean;
alter table public."project_phases" add column if not exists "percent_complete" integer;
alter table public."project_phases" add column if not exists "created_at" timestamptz default now();
alter table public."project_phases" add column if not exists "start_date_target" date;
alter table public."project_phases" add column if not exists "end_date_target" date;
alter table public."project_phases" add column if not exists "start_date_actual" date;
alter table public."project_phases" add column if not exists "end_date_actual" date;
alter table public."project_phases" add column if not exists "internal_notes" text;
alter table public."project_phases" add column if not exists "assigned_to" uuid;
alter table public."project_phases" add column if not exists "budget" numeric;
alter table public."project_phases" add column if not exists "subcontractor_id" uuid;
create table if not exists public."project_staff" (id uuid primary key default gen_random_uuid());
alter table public."project_staff" add column if not exists "company_id" uuid;
alter table public."project_staff" add column if not exists "project_id" uuid;
alter table public."project_staff" add column if not exists "user_id" uuid;
alter table public."project_staff" add column if not exists "role" text;
alter table public."project_staff" add column if not exists "start_date" date;
alter table public."project_staff" add column if not exists "end_date" date;
alter table public."project_staff" add column if not exists "allocation_percent" integer;
alter table public."project_staff" add column if not exists "notes" text;
alter table public."project_staff" add column if not exists "is_active" boolean;
alter table public."project_staff" add column if not exists "created_at" timestamptz default now();
create table if not exists public."project_subcontractors" (id uuid primary key default gen_random_uuid());
alter table public."project_subcontractors" add column if not exists "company_id" uuid;
alter table public."project_subcontractors" add column if not exists "project_id" uuid;
alter table public."project_subcontractors" add column if not exists "phase_id" uuid;
alter table public."project_subcontractors" add column if not exists "subcontractor_id" uuid;
alter table public."project_subcontractors" add column if not exists "status" text;
alter table public."project_subcontractors" add column if not exists "scheduled_start" date;
alter table public."project_subcontractors" add column if not exists "scheduled_end" date;
alter table public."project_subcontractors" add column if not exists "created_at" timestamptz default now();
alter table public."project_subcontractors" add column if not exists "agreed_amount" numeric;
alter table public."project_subcontractors" add column if not exists "role_notes" text;
create table if not exists public."project_tasks" (id uuid primary key default gen_random_uuid());
alter table public."project_tasks" add column if not exists "company_id" uuid;
alter table public."project_tasks" add column if not exists "project_id" uuid;
alter table public."project_tasks" add column if not exists "phase_id" uuid;
alter table public."project_tasks" add column if not exists "title" text;
alter table public."project_tasks" add column if not exists "description" text;
alter table public."project_tasks" add column if not exists "status" text;
alter table public."project_tasks" add column if not exists "due_date_target" date;
alter table public."project_tasks" add column if not exists "assigned_to" uuid[];
alter table public."project_tasks" add column if not exists "created_at" timestamptz default now();
alter table public."project_tasks" add column if not exists "priority" text;
alter table public."project_tasks" add column if not exists "client_id" uuid;
alter table public."project_tasks" add column if not exists "estimated_hours" numeric;
create table if not exists public."project_timeline_events" (id uuid primary key default gen_random_uuid());
alter table public."project_timeline_events" add column if not exists "company_id" uuid;
alter table public."project_timeline_events" add column if not exists "project_id" uuid;
alter table public."project_timeline_events" add column if not exists "title" text;
alter table public."project_timeline_events" add column if not exists "details" text;
alter table public."project_timeline_events" add column if not exists "category" text;
alter table public."project_timeline_events" add column if not exists "event_date" date;
alter table public."project_timeline_events" add column if not exists "client_visible" boolean;
alter table public."project_timeline_events" add column if not exists "created_at" timestamptz default now();
create table if not exists public."projects" (id uuid primary key default gen_random_uuid());
alter table public."projects" add column if not exists "company_id" uuid;
alter table public."projects" add column if not exists "client_id" uuid;
alter table public."projects" add column if not exists "name" text;
alter table public."projects" add column if not exists "status" text;
alter table public."projects" add column if not exists "created_at" timestamptz default now();
alter table public."projects" add column if not exists "quote_id" uuid;
alter table public."projects" add column if not exists "project_number" text;
alter table public."projects" add column if not exists "budget_revenue" numeric;
alter table public."projects" add column if not exists "budget_cost" numeric;
alter table public."projects" add column if not exists "target_end_date" date;
alter table public."projects" add column if not exists "site_address" text;
alter table public."projects" add column if not exists "start_date" date;
alter table public."projects" add column if not exists "budget" numeric;
alter table public."projects" add column if not exists "notes" text;
alter table public."projects" add column if not exists "description" text;
alter table public."projects" add column if not exists "invoice_id" uuid;
create table if not exists public."purchase_order_line_items" (id uuid primary key default gen_random_uuid());
alter table public."purchase_order_line_items" add column if not exists "company_id" uuid;
alter table public."purchase_order_line_items" add column if not exists "purchase_order_id" uuid;
alter table public."purchase_order_line_items" add column if not exists "product_id" uuid;
alter table public."purchase_order_line_items" add column if not exists "item_name" text;
alter table public."purchase_order_line_items" add column if not exists "description" text;
alter table public."purchase_order_line_items" add column if not exists "quantity" numeric;
alter table public."purchase_order_line_items" add column if not exists "unit" text;
alter table public."purchase_order_line_items" add column if not exists "unit_cost" numeric;
alter table public."purchase_order_line_items" add column if not exists "taxable" boolean;
alter table public."purchase_order_line_items" add column if not exists "display_order" integer;
alter table public."purchase_order_line_items" add column if not exists "created_at" timestamptz default now();
create table if not exists public."purchase_orders" (id uuid primary key default gen_random_uuid());
alter table public."purchase_orders" add column if not exists "company_id" uuid;
alter table public."purchase_orders" add column if not exists "vendor_id" uuid;
alter table public."purchase_orders" add column if not exists "project_id" uuid;
alter table public."purchase_orders" add column if not exists "po_number" text;
alter table public."purchase_orders" add column if not exists "status" text;
alter table public."purchase_orders" add column if not exists "order_date" date;
alter table public."purchase_orders" add column if not exists "expected_delivery_date" date;
alter table public."purchase_orders" add column if not exists "actual_delivery_date" date;
alter table public."purchase_orders" add column if not exists "shipping_address" text;
alter table public."purchase_orders" add column if not exists "notes" text;
alter table public."purchase_orders" add column if not exists "terms" text;
alter table public."purchase_orders" add column if not exists "subtotal" numeric;
alter table public."purchase_orders" add column if not exists "tax" numeric;
alter table public."purchase_orders" add column if not exists "total" numeric;
alter table public."purchase_orders" add column if not exists "vendor_quote_attachment" text;
alter table public."purchase_orders" add column if not exists "created_at" timestamptz default now();
create table if not exists public."quote_approvals" (id uuid primary key default gen_random_uuid());
alter table public."quote_approvals" add column if not exists "company_id" uuid;
alter table public."quote_approvals" add column if not exists "quote_id" uuid;
alter table public."quote_approvals" add column if not exists "client_id" uuid;
alter table public."quote_approvals" add column if not exists "approval_token" text;
alter table public."quote_approvals" add column if not exists "approval_status" text;
alter table public."quote_approvals" add column if not exists "signer_name" text;
alter table public."quote_approvals" add column if not exists "signer_email" text;
alter table public."quote_approvals" add column if not exists "client_ip" text;
alter table public."quote_approvals" add column if not exists "sent_at" timestamptz;
alter table public."quote_approvals" add column if not exists "viewed_at" timestamptz;
alter table public."quote_approvals" add column if not exists "signed_at" timestamptz;
alter table public."quote_approvals" add column if not exists "created_at" timestamptz default now();
create table if not exists public."quote_line_items" (id uuid primary key default gen_random_uuid());
alter table public."quote_line_items" add column if not exists "company_id" uuid;
alter table public."quote_line_items" add column if not exists "quote_id" uuid;
alter table public."quote_line_items" add column if not exists "phase_id" uuid;
alter table public."quote_line_items" add column if not exists "product_id" uuid;
alter table public."quote_line_items" add column if not exists "name" text;
alter table public."quote_line_items" add column if not exists "description" text;
alter table public."quote_line_items" add column if not exists "quantity" numeric;
alter table public."quote_line_items" add column if not exists "unit" text;
alter table public."quote_line_items" add column if not exists "unit_cost" numeric;
alter table public."quote_line_items" add column if not exists "unit_price" numeric;
alter table public."quote_line_items" add column if not exists "taxable" boolean;
alter table public."quote_line_items" add column if not exists "photo_url" text;
alter table public."quote_line_items" add column if not exists "is_optional" boolean;
alter table public."quote_line_items" add column if not exists "default_selected" boolean;
alter table public."quote_line_items" add column if not exists "display_order" integer;
alter table public."quote_line_items" add column if not exists "is_material" boolean;
alter table public."quote_line_items" add column if not exists "supplier" text;
alter table public."quote_line_items" add column if not exists "material_cost" numeric;
alter table public."quote_line_items" add column if not exists "labor_cost" numeric;
create table if not exists public."quote_locks" (id uuid primary key default gen_random_uuid());
alter table public."quote_locks" add column if not exists "company_id" uuid;
alter table public."quote_locks" add column if not exists "quote_id" uuid;
alter table public."quote_locks" add column if not exists "locked_by_user_id" uuid;
alter table public."quote_locks" add column if not exists "locked_by_user_name" text;
alter table public."quote_locks" add column if not exists "locked_at" timestamptz;
alter table public."quote_locks" add column if not exists "last_heartbeat" timestamptz;
create table if not exists public."quote_payment_schedules" (id uuid primary key default gen_random_uuid());
alter table public."quote_payment_schedules" add column if not exists "company_id" uuid;
alter table public."quote_payment_schedules" add column if not exists "quote_id" uuid;
alter table public."quote_payment_schedules" add column if not exists "payment_name" text;
alter table public."quote_payment_schedules" add column if not exists "due_event" text;
alter table public."quote_payment_schedules" add column if not exists "amount" numeric;
alter table public."quote_payment_schedules" add column if not exists "amount_type" text;
alter table public."quote_payment_schedules" add column if not exists "percentage" numeric;
alter table public."quote_payment_schedules" add column if not exists "sort_order" integer;
create table if not exists public."quote_phases" (id uuid primary key default gen_random_uuid());
alter table public."quote_phases" add column if not exists "company_id" uuid;
alter table public."quote_phases" add column if not exists "quote_id" uuid;
alter table public."quote_phases" add column if not exists "phase_name" text;
alter table public."quote_phases" add column if not exists "scope_of_work" text;
alter table public."quote_phases" add column if not exists "show_scope_to_client" boolean;
alter table public."quote_phases" add column if not exists "internal_notes" text;
alter table public."quote_phases" add column if not exists "photos" text[];
alter table public."quote_phases" add column if not exists "sort_order" integer;
alter table public."quote_phases" add column if not exists "is_optional" boolean;
alter table public."quote_phases" add column if not exists "default_selected" boolean;
create table if not exists public."quote_views" (id uuid primary key default gen_random_uuid());
alter table public."quote_views" add column if not exists "company_id" uuid;
alter table public."quote_views" add column if not exists "quote_id" uuid;
alter table public."quote_views" add column if not exists "viewer_type" text;
alter table public."quote_views" add column if not exists "viewed_at" timestamptz;
create table if not exists public."quotes" (id uuid primary key default gen_random_uuid());
alter table public."quotes" add column if not exists "company_id" uuid;
alter table public."quotes" add column if not exists "client_id" uuid;
alter table public."quotes" add column if not exists "quote_number" text;
alter table public."quotes" add column if not exists "title" text;
alter table public."quotes" add column if not exists "status" text;
alter table public."quotes" add column if not exists "total" numeric;
alter table public."quotes" add column if not exists "margin" numeric;
alter table public."quotes" add column if not exists "overall_scope" text;
alter table public."quotes" add column if not exists "pdf_customization_settings" jsonb;
alter table public."quotes" add column if not exists "client_selected_items" jsonb;
alter table public."quotes" add column if not exists "is_template" boolean;
alter table public."quotes" add column if not exists "created_at" timestamptz default now();
alter table public."quotes" add column if not exists "client_message" text;
alter table public."quotes" add column if not exists "notes" text;
alter table public."quotes" add column if not exists "terms" text;
alter table public."quotes" add column if not exists "deposit_amount" numeric;
alter table public."quotes" add column if not exists "discount_amount" numeric;
alter table public."quotes" add column if not exists "discount_type" text;
alter table public."quotes" add column if not exists "discount_percentage" numeric;
alter table public."quotes" add column if not exists "show_discount_amount" boolean;
alter table public."quotes" add column if not exists "has_payment_schedule" boolean;
alter table public."quotes" add column if not exists "hero_image_url" text;
alter table public."quotes" add column if not exists "end_photos" text[];
alter table public."quotes" add column if not exists "documents" jsonb;
alter table public."quotes" add column if not exists "margin_adjustment_type" text;
alter table public."quotes" add column if not exists "subtotal" numeric;
alter table public."quotes" add column if not exists "tax" numeric;
alter table public."quotes" add column if not exists "site_address" text;
alter table public."quotes" add column if not exists "pdf_customization_settings_json" text;
alter table public."quotes" add column if not exists "show_overall_scope" boolean;
alter table public."quotes" add column if not exists "issue_date" date;
alter table public."quotes" add column if not exists "expiry_date" date;
alter table public."quotes" add column if not exists "client_selected_items_json" text;
alter table public."quotes" add column if not exists "lead_id" uuid;
alter table public."quotes" add column if not exists "automation_stage" integer;
alter table public."quotes" add column if not exists "client_goals_notes" text;
alter table public."quotes" add column if not exists "client_signature" text;
alter table public."quotes" add column if not exists "cover_page_subtitle" text;
alter table public."quotes" add column if not exists "cover_page_title" text;
alter table public."quotes" add column if not exists "sent_at" date;
alter table public."quotes" add column if not exists "signed_at" text;
alter table public."quotes" add column if not exists "signed_by" text;
alter table public."quotes" add column if not exists "viewed_at" date;
alter table public."quotes" add column if not exists "is_archived" boolean;
alter table public."quotes" add column if not exists "updated_at" timestamptz default now();
alter table public."quotes" add column if not exists "user_id" uuid;
create table if not exists public."resource_allocations" (id uuid primary key default gen_random_uuid());
alter table public."resource_allocations" add column if not exists "company_id" uuid;
alter table public."resource_allocations" add column if not exists "project_id" uuid;
alter table public."resource_allocations" add column if not exists "task_id" uuid;
alter table public."resource_allocations" add column if not exists "user_id" uuid;
alter table public."resource_allocations" add column if not exists "allocation_percentage" numeric;
alter table public."resource_allocations" add column if not exists "start_date" date;
alter table public."resource_allocations" add column if not exists "end_date" date;
alter table public."resource_allocations" add column if not exists "created_at" timestamptz default now();
create table if not exists public."schedule_jobs" (id uuid primary key default gen_random_uuid());
alter table public."schedule_jobs" add column if not exists "company_id" uuid;
alter table public."schedule_jobs" add column if not exists "project_id" uuid;
alter table public."schedule_jobs" add column if not exists "title" text;
alter table public."schedule_jobs" add column if not exists "start_date_time" timestamptz;
alter table public."schedule_jobs" add column if not exists "end_date_time" timestamptz;
alter table public."schedule_jobs" add column if not exists "address" text;
alter table public."schedule_jobs" add column if not exists "status" text;
alter table public."schedule_jobs" add column if not exists "created_at" timestamptz default now();
create table if not exists public."subcontractors" (id uuid primary key default gen_random_uuid());
alter table public."subcontractors" add column if not exists "company_id" uuid;
alter table public."subcontractors" add column if not exists "company_name" text;
alter table public."subcontractors" add column if not exists "trade" text;
alter table public."subcontractors" add column if not exists "contact_name" text;
alter table public."subcontractors" add column if not exists "phone" text;
alter table public."subcontractors" add column if not exists "email" text;
alter table public."subcontractors" add column if not exists "created_at" timestamptz default now();
alter table public."subcontractors" add column if not exists "wcb_policy" text;
alter table public."subcontractors" add column if not exists "insurance_expiry" date;
alter table public."subcontractors" add column if not exists "notes" text;
alter table public."subcontractors" add column if not exists "is_active" boolean;
create table if not exists public."subscription_plans" (id uuid primary key default gen_random_uuid());
alter table public."subscription_plans" add column if not exists "name" text;
alter table public."subscription_plans" add column if not exists "price_monthly" numeric;
alter table public."subscription_plans" add column if not exists "max_users" integer;
alter table public."subscription_plans" add column if not exists "max_quotes_per_month" integer;
alter table public."subscription_plans" add column if not exists "features" jsonb;
create table if not exists public."task_dependencies" (id uuid primary key default gen_random_uuid());
alter table public."task_dependencies" add column if not exists "company_id" uuid;
alter table public."task_dependencies" add column if not exists "project_id" uuid;
alter table public."task_dependencies" add column if not exists "task_id" uuid;
alter table public."task_dependencies" add column if not exists "depends_on_task_id" uuid;
alter table public."task_dependencies" add column if not exists "dependency_type" text;
alter table public."task_dependencies" add column if not exists "created_at" timestamptz default now();
create table if not exists public."tasks" (id uuid primary key default gen_random_uuid());
alter table public."tasks" add column if not exists "company_id" uuid;
alter table public."tasks" add column if not exists "title" text;
alter table public."tasks" add column if not exists "status" text;
alter table public."tasks" add column if not exists "due_date" timestamptz;
alter table public."tasks" add column if not exists "created_at" timestamptz default now();
alter table public."tasks" add column if not exists "client_id" uuid;
alter table public."tasks" add column if not exists "project_id" uuid;
alter table public."tasks" add column if not exists "lead_id" uuid;
alter table public."tasks" add column if not exists "vendor_id" uuid;
alter table public."tasks" add column if not exists "assigned_to" text;
alter table public."tasks" add column if not exists "task_type" text;
alter table public."tasks" add column if not exists "priority" text;
alter table public."tasks" add column if not exists "description" text;
alter table public."tasks" add column if not exists "estimated_hours" numeric;
create table if not exists public."team_invites" (id uuid primary key default gen_random_uuid());
alter table public."team_invites" add column if not exists "company_id" uuid;
alter table public."team_invites" add column if not exists "email" text;
alter table public."team_invites" add column if not exists "role" text;
alter table public."team_invites" add column if not exists "created_at" timestamptz default now();
alter table public."team_invites" add column if not exists "full_name" text;
alter table public."team_invites" add column if not exists "hourly_rate" numeric;
alter table public."team_invites" add column if not exists "is_pending" boolean;
create table if not exists public."time_entries" (id uuid primary key default gen_random_uuid());
alter table public."time_entries" add column if not exists "company_id" uuid;
alter table public."time_entries" add column if not exists "project_id" uuid;
alter table public."time_entries" add column if not exists "employee_name" text;
alter table public."time_entries" add column if not exists "date" date;
alter table public."time_entries" add column if not exists "total_hours" numeric;
alter table public."time_entries" add column if not exists "clock_in" timestamptz;
alter table public."time_entries" add column if not exists "clock_out" timestamptz;
alter table public."time_entries" add column if not exists "entry_type" text;
alter table public."time_entries" add column if not exists "status" text;
alter table public."time_entries" add column if not exists "approved_by" text;
alter table public."time_entries" add column if not exists "notes" text;
alter table public."time_entries" add column if not exists "created_at" timestamptz default now();
alter table public."time_entries" add column if not exists "qbo_time_activity_id" text;
alter table public."time_entries" add column if not exists "qbo_sync_status" text;
alter table public."time_entries" add column if not exists "qbo_sync_error" text;
alter table public."time_entries" add column if not exists "user_id" uuid;
create table if not exists public."time_logs" (id uuid primary key default gen_random_uuid());
alter table public."time_logs" add column if not exists "company_id" uuid;
alter table public."time_logs" add column if not exists "project_id" uuid;
alter table public."time_logs" add column if not exists "task_id" uuid;
alter table public."time_logs" add column if not exists "hours" numeric;
alter table public."time_logs" add column if not exists "date" date;
alter table public."time_logs" add column if not exists "notes" text;
alter table public."time_logs" add column if not exists "billable" boolean;
alter table public."time_logs" add column if not exists "created_at" timestamptz default now();
create table if not exists public."time_off_requests" (id uuid primary key default gen_random_uuid());
alter table public."time_off_requests" add column if not exists "company_id" uuid;
alter table public."time_off_requests" add column if not exists "employee_name" text;
alter table public."time_off_requests" add column if not exists "type" text;
alter table public."time_off_requests" add column if not exists "start_date" date;
alter table public."time_off_requests" add column if not exists "end_date" date;
alter table public."time_off_requests" add column if not exists "total_days" numeric;
alter table public."time_off_requests" add column if not exists "reason" text;
alter table public."time_off_requests" add column if not exists "status" text;
alter table public."time_off_requests" add column if not exists "admin_notes" text;
alter table public."time_off_requests" add column if not exists "created_at" timestamptz default now();
create table if not exists public."users" (id uuid primary key default gen_random_uuid());
alter table public."users" add column if not exists "company_id" uuid;
alter table public."users" add column if not exists "full_name" text;
alter table public."users" add column if not exists "email" text;
alter table public."users" add column if not exists "role" text;
alter table public."users" add column if not exists "created_at" timestamptz default now();
create table if not exists public."vendor_requests" (id uuid primary key default gen_random_uuid());
alter table public."vendor_requests" add column if not exists "company_id" uuid;
alter table public."vendor_requests" add column if not exists "vendor_id" uuid;
alter table public."vendor_requests" add column if not exists "project_id" uuid;
alter table public."vendor_requests" add column if not exists "lead_id" uuid;
alter table public."vendor_requests" add column if not exists "client_id" uuid;
alter table public."vendor_requests" add column if not exists "created_by" uuid;
alter table public."vendor_requests" add column if not exists "title" text;
alter table public."vendor_requests" add column if not exists "scope_of_work" text;
alter table public."vendor_requests" add column if not exists "priority" text;
alter table public."vendor_requests" add column if not exists "due_date" date;
alter table public."vendor_requests" add column if not exists "status" text;
alter table public."vendor_requests" add column if not exists "attachments" jsonb;
alter table public."vendor_requests" add column if not exists "created_at" timestamptz default now();
create table if not exists public."vendors" (id uuid primary key default gen_random_uuid());
alter table public."vendors" add column if not exists "company_id" uuid;
alter table public."vendors" add column if not exists "name" text;
alter table public."vendors" add column if not exists "contact_name" text;
alter table public."vendors" add column if not exists "email" text;
alter table public."vendors" add column if not exists "phone" text;
alter table public."vendors" add column if not exists "address" text;
alter table public."vendors" add column if not exists "category" text;
alter table public."vendors" add column if not exists "notes" text;
alter table public."vendors" add column if not exists "preferred" boolean;
alter table public."vendors" add column if not exists "rating" integer;
alter table public."vendors" add column if not exists "projects_worked_on" jsonb;
alter table public."vendors" add column if not exists "invoice_urls" jsonb;
alter table public."vendors" add column if not exists "created_date" timestamptz;
