import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('confirmed deposits, payment retries, company isolation, project cap and purchased seats',async()=>{
 const db=new PGlite();try{
  await db.exec(await readFile(new URL('../notifications/schema.sql',import.meta.url),'utf8'));
  await db.exec(`create or replace function public.get_auth_company_id() returns uuid language sql stable security definer as $$select company_id from public.profiles where id=auth.uid()$$;
  create schema vault;create table vault.decrypted_secrets(name text,decrypted_secret text,created_at timestamptz default now());insert into vault.decrypted_secrets(name,decrypted_secret) values('fuzedflow_stripe_connect_webhook','synthetic-key');
  create table invoice_payment_schedules(id uuid primary key default gen_random_uuid(),company_id uuid,invoice_id uuid,amount_type text,percentage numeric,amount numeric,amount_paid numeric default 0,sort_order int,status text);
  grant all on all tables in schema public to anon,authenticated,service_role;`);
  for(const table of ['quote_phases','quote_line_items','invoice_phases','invoice_line_items','purchase_order_line_items','change_order_phases','change_order_line_items'])await db.exec(`create table ${table}(id uuid primary key default gen_random_uuid(),company_id uuid);grant all on ${table} to authenticated,service_role;`);
  for(const name of ['20261004201943_storefront_review_repairs.sql','20261004204119_project_tenant_boundaries.sql','20261004205809_storefront_enquiries.sql','20261004210507_reviewed_schedule_drafts.sql','20261004222930_stripe_connect_webhook_secret.sql'])await db.exec(await readFile(new URL('../../supabase/migrations/'+name,import.meta.url),'utf8'));
  await db.exec(`grant all on all tables in schema public to service_role;create policy old_broad_profiles on profiles for all to authenticated using(true) with check(true);create policy old_broad_invoices on invoices for all to authenticated using(true) with check(true);`);
  await db.query("insert into companies(id,name,plan_id,max_users) values($1,'Synthetic A','starter',1),($2,'Synthetic B','professional',4)",[id(1),id(2)]);
  await db.query("insert into profiles(id,company_id,role,email) values($1,$2,'admin','fixture@example.test'),($3,$4,'admin','other@example.test')",[id(10),id(1),id(11),id(2)]);
  await db.query("insert into quotes(id,company_id,status,total,deposit_amount) values($1,$2,'Approved',1000,200)",[id(20),id(1)]);
  const record=async(session,invoice,quote,amount)=>db.query("select record_checkout_payment($1,$2,$3,$4,$5,'2026-10-04') result",[session,id(1),invoice,quote,amount]);
  let payment=await record('cs_deposit',null,id(20),200);assert.equal(payment.rows[0].result.duplicate,false);
  payment=await record('cs_deposit',null,id(20),200);assert.equal(payment.rows[0].result.duplicate,true);
  assert.equal((await db.query('select deposit_paid_amount,status from quotes where id=$1',[id(20)])).rows[0].status,'Approved');
  await db.query("insert into invoices(id,company_id,quote_id,total,status) values($1,$2,$3,1000,'Sent')",[id(30),id(1),id(20)]);
  let invoice=(await db.query('select * from invoices where id=$1',[id(30)])).rows[0];assert.equal(Number(invoice.amount_paid),200);assert.equal(Number(invoice.balance_due),800);
  assert.equal((await db.query('select invoice_id from payments where stripe_checkout_session_id=$1',['cs_deposit'])).rows[0].invoice_id,id(30));
  await db.query("insert into invoice_payment_schedules(company_id,invoice_id,amount_type,amount,amount_paid,sort_order,status) values($1,$2,'fixed',400,200,1,'Partial'),($1,$2,'fixed',600,0,2,'Pending')",[id(1),id(30)]);
  await record('cs_partial',id(30),null,300);await record('cs_partial',id(30),null,300);
  invoice=(await db.query('select * from invoices where id=$1',[id(30)])).rows[0];assert.equal(Number(invoice.amount_paid),500);assert.equal(Number(invoice.balance_due),500);
  const schedules=(await db.query('select amount_paid,status from invoice_payment_schedules order by sort_order')).rows;assert.equal(Number(schedules[0].amount_paid),400);assert.equal(schedules[0].status,'Paid');assert.equal(Number(schedules[1].amount_paid),100);
  await assert.rejects(db.query("select record_checkout_payment('bad',$1,$2,null,10,current_date)",[id(2),id(30)]),/mismatch/);
  for(let n=40;n<45;n++)await db.query("insert into projects(id,company_id,status,name) values($1,$2,'Active','Synthetic project')",[id(n),id(1)]);
  await assert.rejects(db.query("insert into projects(company_id,status) values($1,'Active')",[id(1)]),/5 active projects/);
  await db.query("update projects set status='Completed' where id=$1",[id(40)]);await db.query("insert into projects(company_id,status) values($1,'Active')",[id(1)]);
  await db.query("insert into projects(company_id,status) values($1,'Active')",[id(2)]);
  for(let n=0;n<3;n++)await db.query("insert into team_invites(company_id,email,is_pending) values($1,$2,true)",[id(2),`invited${n}@example.test`]);
  await assert.rejects(db.query("insert into team_invites(company_id,email,is_pending) values($1,'limit@example.test',true)",[id(2)]),/PLAN LIMIT/);
  await db.query("insert into profiles(company_id,role,email) values($1,'employee','invited0@example.test')",[id(2)]);
  await db.query("update team_invites set is_pending=false where email='invited0@example.test'");
  await db.query("insert into profiles(id,company_id,role,email,is_active) values($1,$2,'employee','disabled@example.test',false)",[id(12),id(2)]);
  await assert.rejects(db.query('update profiles set is_active=true where id=$1',[id(12)]),/PLAN LIMIT/);
  await db.query('update companies set max_users=5 where id=$1',[id(2)]);await db.query('update profiles set is_active=true where id=$1',[id(12)]);
  await db.query("insert into project_schedule_drafts(id,company_id,project_id,user_id,schedule) values($1,$2,$3,$4,$5)",[id(60),id(1),id(41),id(10),JSON.stringify({timeline:{project_start:'2026-10-05',project_end:'2026-10-16'},phases:[{tasks:[{title:'Review the work',description:'Unassigned planning placeholder',priority:'Medium',due_date:'2026-10-06',estimated_hours:0}]}]})]);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id(10)]);await db.exec('set role authenticated');
  assert.equal((await db.query('select apply_project_schedule($1) count',[id(60)])).rows[0].count,1);assert.equal((await db.query('select apply_project_schedule($1) count',[id(60)])).rows[0].count,0);
  assert.equal((await db.query('select distinct company_id from projects')).rows.length,1);
  await assert.rejects(db.query("insert into projects(company_id,status) values($1,'Lead')",[id(2)]),/row-level security/);
  await assert.rejects(db.query("update companies set max_users=100 where id=$1",[id(1)]),/managed by the payment service/);
  await assert.rejects(db.query("select record_checkout_payment('forged',$1,$2,null,10,current_date)",[id(1),id(30)]),/permission denied/);
  await assert.rejects(db.query('select review_connect_webhook_secret()'),/permission denied/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id(11)]);await assert.rejects(db.query('select apply_project_schedule($1)',[id(60)]),/Draft unavailable/);
  await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from projects'),/permission denied/);await assert.rejects(db.query('update projects set name=\'changed\''),/permission denied/);await assert.rejects(db.query('select review_connect_webhook_secret()'),/permission denied/);
  await db.exec('reset role;set role service_role');assert.equal((await db.query('select review_connect_webhook_secret() value')).rows[0].value,'synthetic-key');
 }finally{await db.close();}
});
