import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';
import {getPlanIdFromPrice,getUserLimitFromQuantity,getUsdPriceId} from '../../supabase/functions/_shared/subscriptionPlans.js';import {currencyFactor} from '../../supabase/functions/_shared/checkout.js';
async function handler(fail=false){let fn;const payments=[],updates=[];class Stripe{static createFetchHttpClient(){return {}}static createSubtleCryptoProvider(){return {}}webhooks={constructEventAsync:async body=>JSON.parse(body)};subscriptions={retrieve:async()=>({customer:'cus_fixture',status:'active',items:{data:[{price:{id:'price_1UMs8NIfI96QPT6l4fb4CV40'},quantity:2}]}})}};
 const db={rpc:async(name,args)=>{payments.push({name,args});return{error:fail?new Error('database unavailable'):null}},from:()=>({update:values=>({eq:async()=>{updates.push(values);return{error:fail?new Error('database unavailable'):null}}})})};
 let source=await readFile(new URL('../../supabase/functions/stripe-webhook/index.ts',import.meta.url),'utf8');source=stripTypeScriptTypes(source.replace(/^import .*\n/gm,''));new vm.Script(source).runInContext(vm.createContext({Stripe,createClient:()=>db,getPlanIdFromPrice,getUserLimitFromQuantity,getUsdPriceId,currencyFactor,Deno:{env:{get:()=> 'fixture'},serve:f=>{fn=f}},Response,Date,console}));return{fn,payments,updates};
}
const request=(type,object)=>new Request('https://example.test',{method:'POST',headers:{'Stripe-Signature':'fixture'},body:JSON.stringify({type,created:1791130000,data:{object}})});
test('unpaid delayed checkout cannot record a payment; successful delayed payment can',async()=>{const h=await handler();const s={id:'cs_fixture',mode:'payment',payment_status:'unpaid',amount_total:20000,currency:'usd',metadata:{company_id:'company_fixture',invoice_id:'invoice_fixture'}};await h.fn(request('checkout.session.completed',s));assert.equal(h.payments.length,0);await h.fn(request('checkout.session.async_payment_succeeded',{...s,payment_status:'paid'}));assert.equal(h.payments.length,1);assert.equal(h.payments[0].args.p_amount,200);assert.equal(h.payments[0].args.p_invoice,'invoice_fixture');});
test('database failure is retryable and signature is required',async()=>{const h=await handler(true);assert.equal((await h.fn(request('checkout.session.completed',{id:'cs_fixture',mode:'payment',payment_status:'paid',amount_total:1000,currency:'usd',metadata:{company_id:'c',quote_id:'q'}}))).status,500);assert.equal((await h.fn(new Request('https://example.test',{method:'POST'}))).status,400);});
test('subscription checkout and invoice lifecycle synchronize paid seats',async()=>{const h=await handler();await h.fn(request('checkout.session.completed',{mode:'subscription',subscription:'sub_fixture'}));assert.equal(h.updates[0].max_users,4);await h.fn(request('invoice.paid',{parent:{subscription_details:{subscription:'sub_fixture'}}}));assert.equal(h.updates.length,2);assert.equal(h.updates[1].plan_id,'professional');});
